import 'bootstrap/dist/css/bootstrap.min.css' ;
import './global.css'
import Navbar from '../components/Navbar';
import Foot from '../components/Foot';

export const metadata = {
  title: 'The imager',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <body>
       <Navbar />
        {children}
        <Foot />

        </body>
    
    </html>
    </>
  )
}
